In [26]:
month = {
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apl',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec',
      

}

months = {
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31,
      

}

date = {
    0: 30,
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31,
      

}

day = ['일', '월', '화', '수', '목', '금', '토']

a=0

for j in range(1, 13):
    print(month[j])
    a += date[j-1]-28
    if a == 7:
        a = 0
    elif a < 8:
        a = a
    elif a < 15:
        a = a - 7
    
    
    for i in range(7):
        print(day[i], end=' ')
    print()
    print('--------------------')
    
    
    
    print((a)*'   ', end='')
    for i in (range(1, date[j]+1)):
        if i == (7-a):
            print(i)
        elif i == (14-a):
            print(i)
        elif i == (21-a):
            print(i)
        elif i == (28-a):
            print(i)
        elif i == (35-a):
            print(i)
        elif i < 10:
            print(i, end='  ')
        else:
            print(i, end=' ')

            
            
    print()
    print()

Jan
일 월 화 수 목 금 토
--------------------
      1  2  3  4  5
6  7  8  9  10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31

Feb
일 월 화 수 목 금 토
--------------------
               1  2
3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28

Mar
일 월 화 수 목 금 토
--------------------
               1  2
3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31

Apl
일 월 화 수 목 금 토
--------------------
   1  2  3  4  5  6
7  8  9  10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30

May
일 월 화 수 목 금 토
--------------------
         1  2  3  4
5  6  7  8  9  10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31

Jun
일 월 화 수 목 금 토
--------------------
                  1
2  3  4  5  6  7  8
9  10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30

Jul
일 월 화 수 목 금 토
--------------------
   1  2  3  4  5  6
7  8  9  10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31

Aug
일 월 화 수 목 금 토
--------------------
            1  2  3
4  5  6  7  8  9  10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31


Sep
일 월 화 수 목 금 토
--------------------
1  2  3  4  5  6  7
8  9  10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30

Oct
일 월 화 수 목 금 토
--------------------
      1  2  3  4  5
6  7  8  9  10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31

Nov
일 월 화 수 목 금 토
--------------------
               1  2
3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30


Dec
일 월 화 수 목 금 토
--------------------
1  2  3  4  5  6  7
8  9  10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30 31

In [36]:
for month, end_date in months.items():
    print(month, '월')
    for yoil in day:
        print(yoil, end= '| ')
    print()
    print('-'*28)
    
    count= 0
    for a in range(1, end_date + 1):
        print(f' {a}', end=' ') if a >= 10 else print(f' {a}', end= '  ')
        count += 1
        if count ==7 and a != end_date:
            print()
            count = 0
            
    print()

1 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30  31
2 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
3 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30  31
4 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30
5 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30  31
6 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30
7 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30  31
8 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30  31
9 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30
10 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30  31
11 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30
12 월
일| 월| 화| 수| 목| 금| 토|
----------------------------
 1   2   3   4   5   6   7
 8   9   10  11  12  13  14
 15  16  17  18  19  20  21
 22  23  24  25  26  27  28
 29  30  31